name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres -p 5432"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Black
        run: |
          black --diff --check src/
          black --diff --check tests/

      - name: Mypy
        run: |
          mypy src
          mypy tests

      - name: Isort
        run: |
          isort --check-only --diff --profile black src/
          isort --check-only --diff --profile black tests/

      - name: Flake8
        run: |
          flake8 src/
          flake8 tests/

      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5433/test_db
        run: pytest
