name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres -p 5432"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5433 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Check running containers
        run: docker ps -a

      - name: Check PostgreSQL port
        run: netstat -tln | grep 5433 || echo "PostgreSQL not listening!"

      - name: Check PostgreSQL logs
        run: docker logs $(docker ps -q --filter "ancestor=postgres:15")

      - name: Check PostgreSQL connections
        run: PGPASSWORD=postgres psql -h localhost -p 5433 -U postgres -d test_db -c "SELECT * FROM pg_stat_activity;"

      - name: Check existing tables
        run: PGPASSWORD=postgres psql -h localhost -p 5433 -U postgres -d test_db -c "\dt"

      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5433/test_db
        run: pytest
